#!/bin/sh

# Set shell to quit if an error occurs
set -e

# Make i3 config dir
mkdir -p "$HOME/.config/i3"

# Create symlinks for .dotfiles not stored in a folder
ln -sf "$PWD/.bash_profile"         "$HOME/.bash_profile"
ln -sf "$PWD/.bashrc"               "$HOME/.bashrc"
ln -sf "$PWD/.profile"              "$HOME/.profile"
ln -sf "$PWD/.profile"              "$HOME/.bash_profile"
ln -sf "$PWD/i3"                    "$HOME/.config/i3"
ln -sf "$PWD/alacritty"             "$HOME/.config/alacritty"
ln -sf "$PWD/tmux/tmux.conf"        "$HOME/.tmux.conf"
ln -sf "$PWD/tmux/tmux.conf.local"  "$HOME/.tmux.conf.local"

# Place scripts folder link in home directory
ln -sf "$PWD/Scripts"       "$HOME/"   

# Run nested installers
for dir_name in vim; do
    cd $dir_name && ./install
    cd -
done

# installs starship. probably shouldn't be here
curl -sS https://starship.rs/install.sh | sh

