#!/bin/sh

# todo some checking for a daily for the current day would be good

# save off the filename based on the current date
filename=$(short_date).md

# save off the absolute file path
filepath="$DAILY/$filename"

# create the file in the daily repo
touch "$filepath"

# write title to top of file
echo "$filename \n---\n" >> "$filepath"

# create a Planned section
echo "### Planned:\n\n" >> "$filepath"

# add recurring tasks/reminders
echo "Recurring tasks/reminders" >> "$filepath"
echo "1. ~30 mins yoga, and ~10 mins affirmations" >> "$filepath"
echo "1. take breaks, and rest eyes" >> "$filepath"
echo "1. school work" >> "$filepath"
echo "1. side courses, projects, open source" >> "$filepath"
echo "1. for breaks: good weather = walk/read outside. otherwise,
read paper books/puzzles/etc. inside" >> "$filepath"

# add section for specific daily tasks
echo "\nDaily tasks:" >> "$filepath"
echo "1. \n" >> "$filepath"

# create a break between planned and done
echo "---\n\n" >> "$filepath"

# create a Done section
echo "### Done:\n\n" >> "$filepath"


# vim into the file for editing
vim "$DAILY/$filename"
