- name: Install scc tool for rhel 9
  hosts: homelab_rhel_family
  tasks:
    # TODO - add conditional to check for presence of scc tool first and exiting if found
    - name: Download scc tool
      get_url:
        url: "https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.10_rhel9_x86_64_bundle.zip"
        dest: "/tmp/"
        mode: 0644

    - name: Download scc gpg key
      get_url:
        url: "https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/RPM-GPG-KEY-scc-5.zip"
        dest: "/tmp/"
        mode: 0644

    - name: Unzip scc tool
      unarchive:
        src: "/tmp/scc-5.10_rhel9_x86_64_bundle.zip"
        dest: "/opt/"
        remote_src: yes
        mode: 0755

    - name: Unzip scc gpg key and store under /etc/pki/rpm-gpg
      unarchive:
        src: "/tmp/RPM-GPG-KEY-scc-5.zip"
        dest: "/etc/pki/rpm-gpg/"
        remote_src: yes
        mode: 0755

    - name: Import scc gpg key
      rpm_key:
        state: present
        key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-scc-5.10"

    - name: Install scc rpm
      dnf:
        name: "/opt/scc-5.10_rhel9_x86_64/scc-5.10.rhel9.x86_64.rpm"
        state: present

    - name: Install httpd for viewing the report
      package:
        name: httpd
        state: present

    - name: Start and enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes



# TODO - could add an additional play in this file for other families if I start using them and if desired to keep all this logic in one file rather than spread across multiple riles i.e. rhel_scc_install... debian_scc_instal... suse_scc_install... arch_scc_install...
